# Generated by Django 2.1.4 on 2018-12-11 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('text', models.TextField(verbose_name='Sinopsis')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('contentvid', models.FileField(upload_to='uploads', verbose_name='Video')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creacion de publicaión')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualización de publicaión')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='blog.Category', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'publicacion',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-created'],
            },
        ),
    ]
